version: '3'

services:
  ros1:
    build: .
    container_name: p500_ros1
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./src:/workspace/src
      - /dev:/dev
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://192.168.1.100:11311}
      - ROS_IP=${ROS_IP:-192.168.100.180}
    working_dir: /workspace
    command: /bin/bash
